<?php

namespace aiddroid\transencrypt;

require_once '../src/TransEncrypt.php';
use aiddroid\transencrypt\TransEncrypt;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-17 at 11:33:40.
 */
class TransEncryptTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TransEncrypt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TransEncrypt;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers aiddroid\transencrypt\TransEncrypt::Encrypt
     * @todo   Implement testEncrypt().
     */
    public function testEncrypt() {
        // Remove the following lines when you implement this test.
        $cipher = base64_decode("5ZVRUYJaCYL/UZdc");
        $this->assertEquals($cipher, $this->object->Encrypt("hello,world!"));
    }

    /**
     * @covers aiddroid\transencrypt\TransEncrypt::Decrypt
     * @todo   Implement testDecrypt().
     */
    public function testDecrypt() {
        // Remove the following lines when you implement this test.
        $cipher = base64_decode("5ZVRUYJaCYL/UZdc");
        $this->assertEquals("hello,world!", $this->object->Decrypt($cipher));
    }

}
